import type { PurchasePlace } from '../location/place';
import { Money } from '../money/money';
import { isSealed } from '../visibility/seal';

/**
 * Purchase aggregate: one state machine whose early states are intent-shaped
 * ("may I buy this?") and late states are transaction-shaped ("I spent this").
 *
 *   DRAFT ──► PENDING_APPROVAL ──► APPROVED ──► COMPLETED ──► REFUNDED
 *     │              │                 │            │
 *     │              ├──► DENIED       └──► CANCELLED
 *     │              └──► CANCELLED
 *     └──► COMPLETED   (approval-exempt direct log)
 *
 * Every transition returns the next snapshot plus an append-only event draft.
 * All functions are pure; time is always passed in.
 */

export type PurchaseState =
	| 'draft'
	| 'pending_approval'
	| 'approved'
	| 'denied'
	| 'cancelled'
	| 'completed'
	| 'refunded'
	| 'held';

export interface Purchase {
	id: string;
	workspaceId: string;
	memberId: string;
	state: PurchaseState;
	itemName: string;
	note: string | null;
	categoryId: string | null;
	merchantId: string | null;
	/** The card this was paid on. Carries no meaning for approval or money —
	 *  it exists so reconciliation can tell one card's statement from another. */
	accountId: string | null;
	requestedAmount: Money;
	approvedAmount: Money | null;
	finalAmount: Money | null;
	sealedUntil: Date | null;
	sealedFromMemberIds: string[];
	requestedAt: Date | null;
	decidedAt: Date | null;
	completedAt: Date | null;
	/** Set when a bank statement line matched and was confirmed — denormalized for hot reads. */
	clearedAt: Date | null;
	lastNudgedAt: Date | null;
	nudgeCount: number;
	/** Set when this purchase was generated by a recurring rule. */
	recurringRuleId: string | null;
	/** Set on refund child rows: the completed purchase being adjusted. */
	parentPurchaseId: string | null;
	/** Snapshot of routing at request time; never re-resolved while pending. */
	approverMemberIds: string[];
	/** Bucket this purchase charges against (withdrawal on completion). */
	bucketId: string | null;
	/** "Sleep on it": when set, the purchase is paused until this instant. */
	heldUntil: Date | null;
	/** Who put it to sleep — the requester or an approver. */
	heldBy: string | null;
	/**
	 * Where the money was spent, when someone chose to record it. Opt-in, never
	 * automatic, and pure annotation: no transition, policy, or seal rule reads
	 * it, so `edit()` leaves it alone and it is changed on its own through
	 * `setPurchasePlace` in any state.
	 */
	place: PurchasePlace | null;
}

export class PurchaseStateError extends Error {
	constructor(message: string) {
		super(message);
		this.name = 'PurchaseStateError';
	}
}

export interface TransitionEvent {
	fromState: PurchaseState | null;
	toState: PurchaseState;
	actorMemberId: string | null;
	reason: string | null;
	amountSnapshot: Money | null;
	at: Date;
	/** Set only by unseal paths: members who were concealed and may now see it. */
	sealOpenedRecipients?: string[];
}

export interface TransitionResult {
	purchase: Purchase;
	event: TransitionEvent;
}

function assertState(p: Purchase, allowed: PurchaseState[], action: string): void {
	if (!allowed.includes(p.state)) {
		throw new PurchaseStateError(`Cannot ${action} a purchase in state '${p.state}'`);
	}
}

function event(
	p: Purchase,
	to: PurchaseState,
	actorMemberId: string | null,
	at: Date,
	reason: string | null = null,
	amountSnapshot: Money | null = null
): TransitionEvent {
	return { fromState: p.state, toState: to, actorMemberId, reason, amountSnapshot, at };
}

/** DRAFT → PENDING_APPROVAL. Approver set must already be resolved and non-empty. */
export function requestApproval(
	p: Purchase,
	approverMemberIds: string[],
	now: Date
): TransitionResult {
	assertState(p, ['draft'], 'request approval for');
	if (approverMemberIds.length === 0) {
		throw new PurchaseStateError('Cannot request approval with no approvers');
	}
	return {
		purchase: {
			...p,
			state: 'pending_approval',
			approverMemberIds: [...approverMemberIds],
			requestedAt: now
		},
		event: event(p, 'pending_approval', p.memberId, now, null, p.requestedAmount)
	};
}

/** DRAFT → APPROVED without an approver: the approval-exempt intent path. */
export function autoApprove(p: Purchase, now: Date, reason: string): TransitionResult {
	assertState(p, ['draft'], 'auto-approve');
	return {
		purchase: { ...p, state: 'approved', approvedAmount: p.requestedAmount, decidedAt: now },
		event: event(p, 'approved', null, now, reason, p.requestedAmount)
	};
}

/** PENDING_APPROVAL → APPROVED (or → COMPLETED when re-approving an overage). */
export function approve(p: Purchase, actorMemberId: string, now: Date): TransitionResult {
	assertState(p, ['pending_approval'], 'approve');
	if (!p.approverMemberIds.includes(actorMemberId)) {
		throw new PurchaseStateError('Only a designated approver can approve this purchase');
	}
	/*
	 * A final amount means the money is already out the door, so approving
	 * completes rather than merely approves. Two different things arrive here
	 * that way, and they are not the same event:
	 *
	 *   - an overage sent back for re-approval, which was approved once already
	 *     and so carries an approvedAmount;
	 *   - a logged purchase ("already bought") awaiting its *first* approval,
	 *     which carries its final amount from creation and has never been
	 *     approved.
	 *
	 * Treating the second as an overage labelled every ordinary log approval
	 * "overage approved", which reads as though someone had overspent.
	 */
	if (p.finalAmount !== null) {
		const isOverage = p.approvedAmount !== null;
		return {
			purchase: {
				...p,
				state: 'completed',
				approvedAmount: p.finalAmount,
				decidedAt: now,
				completedAt: p.completedAt ?? now
			},
			event: event(
				p,
				'completed',
				actorMemberId,
				now,
				isOverage ? 'overage approved' : null,
				p.finalAmount
			)
		};
	}
	return {
		purchase: { ...p, state: 'approved', approvedAmount: p.requestedAmount, decidedAt: now },
		event: event(p, 'approved', actorMemberId, now, null, p.requestedAmount)
	};
}

/** PENDING_APPROVAL → DENIED. */
export function deny(
	p: Purchase,
	actorMemberId: string,
	reason: string | null,
	now: Date
): TransitionResult {
	assertState(p, ['pending_approval'], 'deny');
	if (!p.approverMemberIds.includes(actorMemberId)) {
		throw new PurchaseStateError('Only a designated approver can deny this purchase');
	}
	return {
		purchase: { ...p, state: 'denied', decidedAt: now },
		event: event(p, 'denied', actorMemberId, now, reason)
	};
}

/**
 * DENIED → PENDING_APPROVAL. The requester asks again, with a reason.
 *
 * A denial used to be the end of the road: the row sat there refused, and the
 * only way to raise it again was to type the whole purchase in a second time,
 * which lost the history of having asked and been told no. That is the wrong
 * shape for the thing this app is actually about. People do come back with
 * "it's on sale now" or "I found a cheaper one", and the honest record of that
 * is one purchase with a denial and an appeal on it, not two purchases.
 *
 * The note is required, because an appeal with nothing new to say is just the
 * same request again and the approver has no basis to answer it differently.
 * Approvers are re-resolved by the caller, so an appeal goes to whoever can
 * decide *now* rather than to whoever happened to be named before.
 */
export function appeal(
	p: Purchase,
	actorMemberId: string,
	note: string,
	approverMemberIds: string[],
	now: Date
): TransitionResult {
	assertState(p, ['denied'], 'appeal');
	if (actorMemberId !== p.memberId) {
		throw new PurchaseStateError('Only the requester can appeal a denial');
	}
	if (note.trim().length === 0) {
		throw new PurchaseStateError('Say what has changed since it was denied');
	}
	if (approverMemberIds.length === 0) {
		throw new PurchaseStateError('Cannot appeal with no approvers');
	}
	return {
		purchase: {
			...p,
			state: 'pending_approval',
			approverMemberIds: [...approverMemberIds],
			requestedAt: now,
			decidedAt: null
		},
		event: event(p, 'pending_approval', actorMemberId, now, `appealed: ${note.trim()}`)
	};
}

/**
 * DENIED → APPROVED. An approver changes their mind, on the record.
 *
 * Deliberately not a silent re-decision. Overturning a "no" is exactly the kind
 * of act that people need to be able to point at afterwards, so the note is
 * required and lands in the same event log as the denial it reverses. The two
 * sit next to each other in the history, which is the whole point: the record
 * says it was refused and then allowed, and by whom.
 *
 * Anyone who was a designated approver on the denial may do it. Re-resolving
 * against the current policy would let a change of policy quietly hand someone
 * the power to overturn a decision they were never part of.
 */
export function overrideDenial(
	p: Purchase,
	actorMemberId: string,
	note: string,
	now: Date
): TransitionResult {
	assertState(p, ['denied'], 'override the denial of');
	if (!p.approverMemberIds.includes(actorMemberId)) {
		throw new PurchaseStateError('Only a designated approver can overturn this denial');
	}
	if (note.trim().length === 0) {
		throw new PurchaseStateError('Say why you are allowing it after all');
	}
	const reason = `denial overturned: ${note.trim()}`;
	// Same fork as `approve`: a purchase that already carries a final amount is
	// money out the door, so allowing it completes rather than merely approves.
	if (p.finalAmount !== null) {
		return {
			purchase: {
				...p,
				state: 'completed',
				approvedAmount: p.finalAmount,
				decidedAt: now,
				completedAt: p.completedAt ?? now
			},
			event: event(p, 'completed', actorMemberId, now, reason, p.finalAmount)
		};
	}
	return {
		purchase: { ...p, state: 'approved', approvedAmount: p.requestedAmount, decidedAt: now },
		event: event(p, 'approved', actorMemberId, now, reason, p.requestedAmount)
	};
}

/** DRAFT | PENDING_APPROVAL | APPROVED → CANCELLED, by the requester. */
export function cancel(p: Purchase, actorMemberId: string, now: Date): TransitionResult {
	assertState(p, ['draft', 'pending_approval', 'approved'], 'cancel');
	if (actorMemberId !== p.memberId) {
		throw new PurchaseStateError('Only the requester can cancel a purchase');
	}
	return {
		purchase: { ...p, state: 'cancelled' },
		event: event(p, 'cancelled', actorMemberId, now)
	};
}

/** Final exceeds approved by more than the workspace's re-approval threshold? */
export function needsReapproval(approved: Money, final: Money, thresholdPct: number): boolean {
	if (!Number.isSafeInteger(thresholdPct) || thresholdPct < 0) {
		throw new PurchaseStateError(`Invalid re-approval threshold: ${thresholdPct}`);
	}
	// final > approved * (1 + pct/100), in exact integer arithmetic.
	return final.minor * 100n > approved.minor * BigInt(100 + thresholdPct);
}

/**
 * Complete with a final amount and date.
 * DRAFT → COMPLETED is the approval-exempt direct-log path.
 * APPROVED → COMPLETED, unless the final overshoots the approved amount by more
 * than thresholdPct — then it returns to PENDING_APPROVAL for re-approval,
 * carrying the attempted final amount. Under-spending never re-approves.
 */
export function complete(
	p: Purchase,
	actorMemberId: string,
	final: { amount: Money; at: Date },
	thresholdPct: number,
	now: Date
): TransitionResult {
	assertState(p, ['draft', 'approved'], 'complete');
	if (actorMemberId !== p.memberId) {
		throw new PurchaseStateError('Only the requester can complete a purchase');
	}
	if (final.amount.isNegative || final.amount.isZero) {
		throw new PurchaseStateError('Final amount must be positive');
	}
	// Overage re-approval only applies where approval applied: an auto-approved
	// purchase (exempt or recurring) has no approver snapshot and nobody to ask.
	if (
		p.state === 'approved' &&
		p.approverMemberIds.length > 0 &&
		needsReapproval(p.approvedAmount!, final.amount, thresholdPct)
	) {
		return {
			purchase: {
				...p,
				state: 'pending_approval',
				finalAmount: final.amount,
				completedAt: final.at,
				requestedAt: now,
				lastNudgedAt: null,
				nudgeCount: 0
			},
			event: event(p, 'pending_approval', actorMemberId, now, 'overage', final.amount)
		};
	}
	return {
		purchase: { ...p, state: 'completed', finalAmount: final.amount, completedAt: final.at },
		event: event(p, 'completed', actorMemberId, now, null, final.amount)
	};
}

export interface PurchaseEdit {
	itemName?: string;
	requestedAmount?: Money;
	categoryId?: string | null;
	note?: string | null;
}

/**
 * Edit item/amount/category while DRAFT, PENDING_APPROVAL, or APPROVED.
 * Editing an APPROVED purchase's substance invalidates the approval and
 * returns it to PENDING_APPROVAL. Note-only edits never invalidate.
 */
export function edit(
	p: Purchase,
	actorMemberId: string,
	changes: PurchaseEdit,
	now: Date
): TransitionResult {
	assertState(p, ['draft', 'pending_approval', 'approved'], 'edit');
	if (actorMemberId !== p.memberId) {
		throw new PurchaseStateError('Only the requester can edit a purchase');
	}
	const substantive =
		(changes.itemName !== undefined && changes.itemName !== p.itemName) ||
		(changes.requestedAmount !== undefined && !changes.requestedAmount.equals(p.requestedAmount)) ||
		(changes.categoryId !== undefined && changes.categoryId !== p.categoryId);

	const next: Purchase = {
		...p,
		itemName: changes.itemName ?? p.itemName,
		requestedAmount: changes.requestedAmount ?? p.requestedAmount,
		categoryId: changes.categoryId === undefined ? p.categoryId : changes.categoryId,
		note: changes.note === undefined ? p.note : changes.note
	};

	// An approved purchase with no approvers was never gated: either the policy
	// required no approval, or every approver was concealed and it auto-approved
	// with disclosure. There is no approval to invalidate, and sending it back to
	// pending would strand it — nobody could ever decide it. Apply the edit.
	if (p.state === 'approved' && substantive && p.approverMemberIds.length === 0) {
		return {
			purchase: { ...next, approvedAmount: next.requestedAmount },
			event: event(next, next.state, actorMemberId, now, 'edited', next.requestedAmount)
		};
	}

	if (p.state === 'approved' && substantive) {
		return {
			purchase: {
				...next,
				state: 'pending_approval',
				approvedAmount: null,
				requestedAt: now,
				lastNudgedAt: null,
				nudgeCount: 0
			},
			event: event(
				p,
				'pending_approval',
				actorMemberId,
				now,
				'edited after approval',
				next.requestedAmount
			)
		};
	}
	return {
		purchase: next,
		event: event(next, next.state, actorMemberId, now, 'edited', next.requestedAmount)
	};
}

/**
 * "Sleep on it." PENDING_APPROVAL → HELD, paused until `until`. Either the
 * requester (a self-imposed cooling-off) or a designated approver ("let's think
 * about it") may set it — the caller checks which. Approvers are preserved so
 * the request resumes intact when it wakes.
 */
export function hold(p: Purchase, actorMemberId: string, until: Date, now: Date): TransitionResult {
	// From pending (a request awaiting a decision) or approved (a fresh buy you
	// want to sleep on before spending). Waking restores whichever it was.
	assertState(p, ['pending_approval', 'approved'], 'sleep on');
	if (until.getTime() <= now.getTime()) {
		throw new PurchaseStateError('The pause has to end in the future');
	}
	return {
		purchase: { ...p, state: 'held', heldUntil: until, heldBy: actorMemberId },
		event: event(p, 'held', actorMemberId, now, 'put to sleep', null)
	};
}

/** HELD → HELD: give it a few more days. */
export function extendHold(
	p: Purchase,
	actorMemberId: string,
	until: Date,
	now: Date
): TransitionResult {
	assertState(p, ['held'], 'extend the pause on');
	if (until.getTime() <= now.getTime()) {
		throw new PurchaseStateError('The pause has to end in the future');
	}
	return {
		purchase: { ...p, heldUntil: until },
		event: event(p, 'held', actorMemberId, now, 'wait more', null)
	};
}

/**
 * Still want it. Wake back to where it was: APPROVED if a decision was already
 * in hand (deciding again would let a different approver relitigate what
 * someone already signed off), PENDING_APPROVAL if it is still waiting — which
 * includes an overage bounce-back, whose finalAmount is parked mid-re-approval
 * even though decidedAt survives from the first round. The pending clock
 * restarts so staleness counts from waking, not the first ask.
 */
export function wake(p: Purchase, actorMemberId: string, now: Date): TransitionResult {
	assertState(p, ['held'], 'wake');
	const awaitingDecision = p.decidedAt === null || p.finalAmount !== null;
	if (awaitingDecision) {
		return {
			purchase: {
				...p,
				state: 'pending_approval',
				heldUntil: null,
				heldBy: null,
				requestedAt: now
			},
			event: event(p, 'pending_approval', actorMemberId, now, 'still wanted it', p.requestedAmount)
		};
	}
	return {
		purchase: {
			...p,
			state: 'approved',
			heldUntil: null,
			heldBy: null,
			approvedAmount: p.approvedAmount ?? p.requestedAmount,
			decidedAt: p.decidedAt ?? now
		},
		event: event(p, 'approved', actorMemberId, now, 'still wanted it', p.requestedAmount)
	};
}

/** HELD → CANCELLED: let it go. The quiet win the whole feature is for. */
export function letGo(p: Purchase, actorMemberId: string, now: Date): TransitionResult {
	assertState(p, ['held'], 'let go');
	return {
		purchase: { ...p, state: 'cancelled', heldUntil: null, heldBy: null },
		event: event(p, 'cancelled', actorMemberId, now, 'let it go', p.requestedAmount)
	};
}

/** COMPLETED → REFUNDED once cumulative refunds cover the final amount. */
export function markRefunded(p: Purchase, actorMemberId: string, now: Date): TransitionResult {
	assertState(p, ['completed'], 'refund');
	// A refund on a sealed purchase would leak it through the numbers.
	if (isSealed(p, now)) {
		throw new PurchaseStateError('Sealed purchases cannot be refunded until the seal opens');
	}
	return {
		purchase: { ...p, state: 'refunded' },
		event: event(p, 'refunded', actorMemberId, now, null, p.finalAmount)
	};
}
